#ToDO create a new folders and put there yamls like below:

repo/
│
├── argocd/
│   ├── cluster-ip.yaml
│   └── ingress.yaml
│
├── frontend/
│   ├── deployment.yaml
│   ├── load-balancer.yaml
│   └── ingress.yaml
│
├── backend/
│   ├── deployment.yaml
│   ├── service.yaml
│
├── database/
│   ├── cluster-ip.yaml
│   ├── configmap-and-secret.yaml
│   ├── deployment.yaml
│   ├── pvc-longhorn.yaml
│
├── monitoring/
│   ├── grafana-ingress.yaml
│   └── longhorn-storageclass.yaml
│
└── nginx/
    └── deployment.yaml


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lesniewskii/k8s_deployments_objects.git
    targetRevision: HEAD
    path: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lesniewskii/k8s_deployments_objects.git
    targetRevision: HEAD
    path: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lesniewskii/k8s_deployments_objects.git
    targetRevision: HEAD
    path: database
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lesniewskii/k8s_deployments_objects.git
    targetRevision: HEAD
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
