apiVersion: v1
kind: Service
metadata:
  name: weigh-tracker-backend
spec:
  selector:
    app: weigh-tracker-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
