apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: weight-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: lesiiu/weight-tracker-frontend:1.0.6
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_API_URL
          # value: "http://10.43.183.79:30000"
          value: "http://10.43.183.79:8000"
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "REACT_APP_BACKEND_API_URL=$REACT_APP_BACKEND_API_URL"

    # livenessProbe:
    #   httpGet:
    #     path: /
    #     port: 80
    #   initialDelaySeconds: 15
    #   periodSeconds: 20
