apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  namespace: weight-tracker
spec:
  selector:
    app: react-frontend
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 3000
  type: LoadBalancer

