apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: weight-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: lesiiu/weight-tracker-frontend:1.0.4
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_API_URL
          value: "http://weigh-tracker-backend-service.weight-tracker.svc.cluster.local:8000"
    # livenessProbe:
    #   httpGet:
    #     path: /
    #     port: 80
    #   initialDelaySeconds: 15
    #   periodSeconds: 20
