apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: weight-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: lesiiu/weight-tracker-frontend:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_API_URL
          value: "http://weigh-tracker-backendd.weight-tracker.svc.cluster.local"
