apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
  namespace: longhorn
provisioner: driver.longhorn.io
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
