apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-new
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-new
  resources:
    requests:
      storage: 5Gi