# postgres-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: database
data:
  DB_PORT: "5432"
  DB_NAME: "mydatabase"
  DB_USER: "postgres"
---
# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: database
type: Opaque
data:
  # Note: values must be base64 encoded
  DB_PASSWORD: "eW91cnBhc3N3b3Jk"  # base64 encoded 'yourpassword'

