# postgres-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: weight_tracker
data:
  DB_HOST: "postgres.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "weight_tracker"
  DB_USER: "postgres"
---
# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # Note: values must be base64 encoded
  DB_PASSWORD: "eW91cnBhc3N3b3Jk"  # base64 encoded 'yourpassword'

