apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
  name: argocd-weight-tracker-vps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lesniewskii/k8s_deployments_objects.git
    targetRevision: HEAD
    path: weight-tracker-vps
  destination:
    server: https://kubernetes.default.svc
    namespace: weight-tracker
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
