apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: weight-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: lesiiu/weight-tracker-backend:1.0.7
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_API_URL
          # value: weigh-tracker-backend-service.weight-tracker.svc.cluster.local:8000
          value: "http://weigh-tracker-backend-service:8000"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"