apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  namespace: weight-tracker
spec:
  selector:
    app: react-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30080
    - port: 443
      targetPort: 80
      protocol: TCP
      name: https
      nodePort: 30443
  type: NodePort



# apiVersion: v1
# kind: Service
# metadata:
#   name: react-frontend
# spec:
#   selector:
#     app: react-frontend
#   ports:
#     - protocol: TCP
#       port: 80  # Exposes port 80 to external clients
#       targetPort: 80
#   type: LoadBalancer  # External access to the frontend
